### ISSUE TITLE
Firefox's ajax generates error: "No Transport" while gem newrelic_rpm is enabled in production

### ISSUE THREAD

**Issue by Zhomart** [newrelic/rpm#158]
AJAX requests to same domain in the latest version of firefox generates error "No Transport" in `production` environment.
When I disabled newrelic_rpm gem, ajax requests worked without errors.

But in `staging` environment, which is copy of `production`, ajax requests worked without errors.

In chrome and IE, ajax requests work w/o errors.
- Firefox: 29.0
- Rails 4.0.1
- newrelic_rpm (3.7.3.204)
- jquery-rails (3.1.0)
- jquery 1.11.0

**Comment by justinfoote** [comment]
We are closing this issue due to age.  If this issue is still a problem, please open a new issue, reach out on the New Relic [Explorers Hub](https://discuss.newrelic.com/) or contact [Support](https://support.newrelic.com/).

Thank you!
