### ISSUE TITLE
Manual instrumentation insertion does not work when HTTP streaming is used

### ISSUE THREAD

**Issue by vojtad** [newrelic/rpm#173]
I have set auto_instrumentation to false in newrelic.yml and I use this code

```
<%= ::NewRelic::Agent.browser_timing_header rescue '' %>
```

to manually insert it in application.html.erb. Everything worked perfectly fine until I have enabled HTTP streaming for couple of actions. The instrumentation code is not inserted when HTTP streaming is enabled, however, it still works in actions that do not use render ..., stream: true.

Do you have any idea what could be wrong?

**Comment by justinfoote** [comment]
We are closing this issue due to age.  If this issue is still a problem, please open a new issue, reach out on the New Relic [Explorers Hub](https://discuss.newrelic.com/) or contact [Support](https://support.newrelic.com/).

Thank you!
