### ISSUE TITLE
NoMethodError: undefined method `duration' for nil:NilClass

### ISSUE THREAD

**Issue by PetrKaleta** [newrelic/rpm#176]
For more detail about this issue please check this issue and its discussion https://github.com/mperham/sidekiq/issues/1823

**Comment by justinfoote** [comment]
We are closing this issue due to age.  If this issue is still a problem, please open a new issue, reach out on the New Relic [Explorers Hub](https://discuss.newrelic.com/) or contact [Support](https://support.newrelic.com/).

Thank you!
