### ISSUE TITLE
Proc.new deprecation warnings

### ISSUE THREAD

**Issue by brunocam11** [newrelic/rpm#305]
These deprecation warnings related to Proc.new are constantly appearing.

`/Users/moove-it/.rvm/gems/ruby-2.7.0-preview1/gems/newrelic_rpm-6.7.0.359/lib/new_relic/dependency_detection.rb:97: warning: Capturing the given block using Proc.new is deprecated; use &block instead`

`/Users/moove-it/.rvm/gems/ruby-2.7.0-preview1/gems/newrelic_rpm-6.7.0.359/lib/new_relic/dependency_detection.rb:118: warning: Capturing the given block using Proc.new is deprecated; use &block instead`

**Comment by rachelleahklein** [comment]
Hello, @brunocam11! I'm happy to report we are currently working on support for pre-release versions of Ruby 2.7.0, which will eliminate these warnings. I will follow up when we've released that support.

**Comment by rachelleahklein** [comment]
@brunocam11, just letting you know we released support for Ruby 2.7.0-preview1 today in agent version 6.8.0. With the new version of the agent, you will no longer see these warnings!
