### ISSUE TITLE
translate_exception - Wrong method raises wrong exception

### ISSUE THREAD

**Issue by butterz21217** [newrelic/rpm#309]
The method called in the raise `translate_exception` is the wrong method, which is causing the wrong error message to appear.

https://github.com/newrelic/rpm/blob/7bb753161cf0215a09fd609f39b5a859a9860f49/lib/new_relic/agent/instrumentation/active_record_notifications.rb#L28

The correct method should be `translate_exception_class`.

The error message raised ends up being an ActiveRecord::StatementInvalid with the error message being the sql passed into the method. This prevents ActiveRecord from translating the error into an ActiveRecord::RecordNotUnique.

Thanks

**Comment by rachelleahklein** [comment]
Hi @butterz21217 - thanks for reaching out!

Can you let me know which version of Rails you are using? We do use `translate_exception_class` for versions 4.1 and above of ActiveRecord.

**Comment by butterz21217** [comment]
Hi @rachelleahklein 
The project this was noticed on uses Rails 4.2.6
