### ISSUE TITLE
Allow to configure head tag scan limit for cases when head tag exceeds 50k

### ISSUE THREAD

**Issue by echoAlexey** [newrelic/rpm#311]
https://github.com/newrelic/rpm/blob/1dc18f8afb31463bba56f04666c095a1d87cb3f2/lib/new_relic/rack/browser_monitoring.rb#L20

`NewRelic::Agent.config[:'browser_monitoring.head_scan_limit']`

**Comment by mwlang** [comment]
Hi, @echoAlexey 

That's a good idea!  I have relayed this feature request to our support team and they'll place this feature request through the right channels, so I'm going to close this issue here.
