### ISSUE TITLE
Browser instrumentation injection results in invalid Content-Length headers with latest rack versions

### ISSUE THREAD

**Issue by tanelsuurhans** [newrelic/rpm#313]
There is an issue with Rack versions above `2.0.8` where using agent-based Browser instrumentation injection causing `Content-Length` headers to not match the content size, which in turns causes content truncation in some cases.

I have written a longer investigation in an issue at https://github.com/rack/rack/issues/1504
It seems that the desired fix is to handle this on the RPM side.

**Comment by rachelleahklein** [comment]
Hi @tanelsuurhans. Thanks for reaching out to us about this!

We have actually already received a [pull request](https://github.com/newrelic/rpm/pull/312) fixing this, which we have accepted and plan to include in our next agent release.

**Comment by lmansur** [comment]
Hi @rachelleahklein 

I was just wondering if there's any news on when #312 will be released. My Sidekiq UI is not working due to this issue. Thanks!

**Comment by rachelleahklein** [comment]
Hi, @lmansur. I don't have a specific date to give you for our next release, but we're actively working on it. We will update this issue when the fix is released so you'll know right away.

**Comment by lmansur** [comment]
Thanks @rachelleahklein 👍

**Comment by bbay** [comment]
Hey @tanelsuurhans I somehow pinned down the problem to NewRelic as well but I was going completely crazy for days. Thank you so much for your investigation 👍

Downgrading rack to `2.0.8` did the trick for me.

**Comment by Paul-Yves** [comment]
Hi. I just experienced the same, and downgraded to rack 2.0.9 (which support samesite option on cookies)

**Comment by dentarg** [comment]
Setting `NEW_RELIC_BROWSER_MONITORING_AUTO_INSTRUMENT=false` seems to be a workaround for this (if you don't want to downgrade rack)

**Comment by tannalynn** [comment]
Just letting you know we released the new version 6.9.0 that includes the fix for this! Thanks everyone!
