### ISSUE TITLE
Perhaps the install command could be improved

### ISSUE THREAD

**Issue by flanger001** [newrelic/rpm#315]
Steps to recreate:

- Have an app with an existing `newrelic.yml`
- Run `newrelic install` with any options

```
newrelic.yml file already exists.  Move it out of the way.
```

https://github.com/newrelic/rpm/blob/17734c85a9251ede14fbee517f0d264d99116c7e/lib/new_relic/cli/commands/install.rb#L44

The language could be less blunt, and also this could give the option of overwriting the file instead.

**Comment by rachelleahklein** [comment]
Hi @flanger001, we'll look into the improvement you've suggested - certainly the wording could be kinder, I agree! Thanks for bringing it up.

**Comment by flanger001** [comment]
Thanks @rachelleahklein! I think the more useful thing here would be my second point of optionally overwriting the file. I think it's probably a safe assumption that this file will be in VC.

**Comment by mwlang** [comment]
@flanger001 Thank you for your suggestion.  We have improved `newrelic install` with a `--force` flag and improved messaging.  This will be available in the next release after 6.9.0.

**Comment by flanger001** [comment]
Thank you @mwlang!
