### ISSUE TITLE
What should the value of backport_fast_active_record_connection_lookup be for Rails 5?

### ISSUE THREAD

**Issue by aualdrich** [newrelic/rpm#317]
I noticed that in the 6.5 agent release, there's a recommendation to set the value of backport_fast_active_record_connection_lookup to false. However, I've also seen this is because of a patch that's getting fixed in Rails 6. Our app is currently on Rails 5.1. What should the value of this be, and should we flip it once we upgrade our app to Rails 6? Thanks!

**Comment by mwlang** [comment]
This configuration takes inspiration from how [Rails 6 passes the connection info to notification subscribers](https://github.com/rails/rails/pull/34602) to avoid looping through all connections to find the right one when instrumenting.  The value of this setting is ignored for Rails 6+ apps as it is not needed and essentially ignored.

The recommendation to set the value to `false` by default stems from various external gems that alter or prepend the ActiveRecord notification, thereby breaking instrumentation of ActiveRecord.  The CHANGELOG suggests testing in development environment to ensure other gems your project may depend on are not breaking the instrumentation.  Thus, users must opt-in to this performance enhancement.

If you have other questions or concerns, please feel free to reach out directly to support, who can help you with configuring your environment optimally and answer any other questions you may have.

**Comment by magni-** [comment]
Is there a list of commonly used gems that this setting would conflict with?
