### ISSUE TITLE
Content-Length calculation.

### ISSUE THREAD

**Issue by ioquatix** [newrelic/rpm#318]
Not sure the exact reason but it seems like this code is updating the rack response body without changing the content length, causing:

- https://github.com/rack/rack/issues/1531
- https://github.com/mperham/sidekiq/issues/4440

and others.

**Comment by lmansur** [comment]
There's already a related issue: https://github.com/newrelic/rpm/issues/313

**Comment by ioquatix** [comment]
Awesome looks like it’s already been fixed!
