### ISSUE TITLE
DelayedJobSampler

### ISSUE THREAD

**Issue by yigitbacakoglu** [newrelic/rpm#321]
Hi,

Today we had stress on our delayed job tables, there were more than 50k job was queued and it was increasing. 

We started to monitor the mysql transactions and saw that there are lots of `count` and `group by` queries were being sent to delayed_job table (which we didn't realize before). (We had 120 active workers) which causes huge stress on the table. Because of that stress, our database write latency increased 3x times, database cpu hit to 100% and queued jobs increased to 200k

After hours of investigation of the source of that queries, finally we found that newrelic's DelayedJobSampler class sends that queries. Then we immediately disabled dj sampler and all our resources back to normal.

We are using this gem for more than 5 years with exactly same configs and we didn't realize that queries before, I wonder how that sampler started working suddenly? Is there anything that newrelic enabled recently?

**Comment by rachelleahklein** [comment]
I should also mention that we have not changed our `delayed_job` instrumentation recently or added new functionality.
