### ISSUE TITLE
Incorrect calculation of Content-Length (when injecting Browser Monitoring JS)

### ISSUE THREAD

**Issue by dentarg** [newrelic/rpm#325]
https://github.com/newrelic/rpm/blob/29bc3e0bf6f4d11b21ced7fc38916b9e41f3a680/lib/new_relic/rack/browser_monitoring.rb#L39-L41

`size` only return the character length, we need to length in bytes for this to be correct

I'm trying out newrelic_rpm 6.9.0.363 in my app and `</html>` is missing its end tag because of this (I assume):

<img width="434" alt="Screenshot 2020-03-09 at 18 21 20" src="https://user-images.githubusercontent.com/42626/76240012-cd459e00-6232-11ea-8021-a286c516190e.png">

**Comment by tannalynn** [comment]
Hi @dentarg!
Thanks for letting us know about this issue. We have incorporated a fix for this issue from this [pull request](https://github.com/newrelic/rpm/pull/322) that will be included in the next release of the agent. 
We will let you know here when that version is released!

**Comment by rachelleahklein** [comment]
This fix has been included in version 6.10.0 of the Ruby agent, released today!
