### ISSUE TITLE
unsupported rails version 6.0.2.1

### ISSUE THREAD

**Issue by siraz-provectus** [newrelic/rpm#327]

**Comment by siraz-provectus** [comment]
Caused by:
SSHKit::Command::Failed: rake exit status: 1
rake stdout: rake aborted!
NameError: wrong constant name [[:error, ["detected unsupported rails version 6.0.2.1"], nil]]
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.8.0.341/lib/new_relic/control/class_methods.rb:52:in `const_get'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.8.0.341/lib/new_relic/control/class_methods.rb:52:in `load_framework_class'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.8.0.341/lib/new_relic/control/class_methods.rb:32:in `new_instance'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.8.0.341/lib/new_relic/control/class_methods.rb:13:in `instance'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/newrelic_rpm-4.8.0.341/lib/newrelic_rpm.rb:41:in `block in <class:Railtie>'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
/home/root/apps/cosmos/releases/20200316095749/config/environment.rb:5:in `<main>'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:339:in `require_environment!'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/railties-6.0.2.1/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/home/root/apps/cosmos/shared/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/root/.rbenv/versions/2.6.2/bin/bundle:23:in `load'
/root/.rbenv/versions/2.6.2/bin/bundle:23:in `<main>'

**Comment by tannalynn** [comment]
Hello @ siraz-provectus thanks for letting us know about this.
For issues with the agent we generally recommend working with our Support team, which can be reached directly though support.newrelic.com. We will be monitoring this issue and working with our Support team directly if it turns out any changes need to be made to the Ruby agent to resolve this issue.

**Comment by siraz-provectus** [comment]
I used old agent version. It is works with version 6.9.0.363
