### ISSUE TITLE
Breaking custom http client instrumentation

### ISSUE THREAD

**Issue by alexJunger** [newrelic/rpm#333]
Hello!

We're maintaining an instrumentation plugin for the Manticore JRuby http client. https://github.com/runtastic/newrelic-manticore

We noticed that 6.10 introduced a breaking change for us by renaming the file containing `Agent::HttpClient::AbstractRequest` from `abstract_request.rb` to `abstract.rb`. We require this class to implement a request wrapper used for our instrumentation.

I'd just like to clarify whether this is something we should generally expect to happen at all release levels (including minor/patch) or not? Do you have any standard procedures for compatibility of plugin instrumentation? (The class is marked as public API in its comments.)

Thanks!

**Comment by mwlang** [comment]
@alexJunger, thank you for reaching out to us and also authoring and maintaining one of the many excellent gems out there that enhance the agent's core functionality. 

The recent changes are not historically a typical set of changes we would make.  The 6.10 release touched on almost every instrumentation as we added ability to notice errors at the segment level.  As part of this large effort, we took the opportunity to refactor much of the HTTP client instrumentation and this unfortunately affected your gem adversely. 

As for standard procedures, we've been discussing this more internally and the need to develop and document standards to make it easier to build and maintain plugins and minimize potential to break existing ones like yours.  

The abstract class is still present and I don't believe the API signature itself changed, only the file name was changed and relocated to sub-folder to help organize the project code better.  If the API signature inadvertently changed, please elaborate further on the exact error you're experiencing and we'll try to help resolve it.

**Comment by alexJunger** [comment]
@mwlang got it! And thanks for your efforts in making and keeping the agent extensible!

The Api signature itself didn't change, correct. We simply got a load error due to the changed file name:
```sh
LoadError:
  no such file to load -- new_relic/agent/http_clients/abstract_request
```

**Comment by mwlang** [comment]
Ok, thank you for clarifying.  I have a question for you @alexJunger:

One of the reasons for the extensive changes on HTTP clients is that we refactored to make all the supported HTTP client libraries we auto-instrument capable of capturing the HTTP response codes and error messages at the segment level.  I took a brief look at your gem to see if I could quickly wrap your instrumentation as well, but I wasn't to pull this off in the time I allotted.

Is this something you'd be interested including in a future update of your gem?

**Comment by alexJunger** [comment]
@mwlang that seems worth integrating for sure! Would this data already be used (eg. in APM) or queryable somewhere?

**Comment by rachelleahklein** [comment]
Hi @alexJunger,

When error information is captured at the segment level, error attributes show up on spans in New Relic's Distributed Tracing UI and can also be used to query span events. Check out the [release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/ruby-release-notes/ruby-agent-6100364) for version 6.10 of the agent for more information.
